
- name: Provision OpenShift Dev Spaces
  include_tasks: provision_devspaces.yaml
  vars:
    operators_project: "workshop-operators"
    snapshot_operator_project: "openshift-marketplace"
    che_project: "che"

- name: Provision users workload
  ansible.builtin.include_tasks: provision_users_workload.yaml
