---

- name: Retrieve Number of Users 1/2
  set_fact:
    num_users: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='htpasswd', namespace='openshift-config') | json_query('[0].data')}}"

- name: Retrieve Number of Users 2/2
  set_fact:
    num_users: "{{ num_users | b64decode | regex_findall('user') | length }}"

- name: debug
  debug:
    msg: "Number of users: {{ num_users }}"

- name: Create usernames variable
  ansible.builtin.set_fact:
    users: "{{ users | default([]) + ['user' + item | string] }}"
  loop: "{{ range(1, ((num_users | int) + 1)) | list }}"


# Figure out paths
- name: Get OpenShift Apps Domain
  set_fact:
    route_subdomain: "{{ query('kubernetes.core.k8s', api_version='config.openshift.io/v1', kind='Ingress', resource_name='cluster') | json_query('[0].spec.appsDomain') }}"

- name: Get OpenShift Domain
  set_fact:
    route_subdomain: "{{ query('kubernetes.core.k8s', api_version='config.openshift.io/v1', kind='Ingress', resource_name='cluster') | json_query('[0].spec.domain') }}"
  when:
    - route_subdomain | length == 0

- name: Get OpenShift Console
  set_fact:
    console_url: "{{ query('kubernetes.core.k8s', api_version='config.openshift.io/v1', kind='Console', resource_name='cluster') | json_query('[0].status.consoleURL')  }}"

- name: Get OpenShift API
  set_fact:
    api_url: "{{ query('kubernetes.core.k8s', api_version='config.openshift.io/v1', kind='Infrastructure', resource_name='cluster') | json_query('[0].status.apiServerURL')  }}"

- name: debug
  debug:
    msg: 
    - "Console URL: {{ console_url }}"
    - "API URL: {{ api_url }}"
    - "Route Subdomain: {{ route_subdomain }}"
    - "Admin username: {{ ocp_username }}"

- name: Fetch OpenShift cluster version
  set_fact:
    openshift_version: "{{ query('kubernetes.core.k8s', kind='ClusterOperator', resource_name='openshift-apiserver') | json_query('[0].status.versions[?name==`operator`].version | [0]') | split('.') | slice(2) | first | join('.') }}"
  when: (openshift_version is not defined) or (openshift_version | length == 0)

- name: debug
  debug:
    msg: "Setting up for OpenShift version: {{ openshift_version }}"



- name: Evaluate Full Deployment
  include_tasks: main_all.yaml




