---

- name: Retrieve Number of Users 1/2
  set_fact:
    num_users: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='htpasswd', namespace='openshift-config') | json_query('[0].data')}}"

- name: Retrieve Number of Users 2/2
  set_fact:
    num_users: "{{ num_users | b64decode | regex_findall('user') | length }}"

- name: Retrieve Number of Users 2/2
  set_fact:
    num_users: "1"

- name: Remove User Workspaces
  include_tasks: remove_user_devworkspaces.yaml

# - name: Uninstall DevSpaces
#   include_tasks: remove_devspaces.yaml
#   vars:
#     operators_project: 'workshop-operators'
#     che_project: "che"

- name: Delete namespace userX-devspaces
  k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: 'user{{item}}-devspaces'
  with_sequence: start=1 end={{ num_users }}

- name: Remove Shared Resources
  include_tasks: remove_shared_database.yaml





# Leave this as the last task in the playbook.
# - name: Remove workload tasks complete
#   debug:
#     msg: "Remove Workload Tasks completed successfully."
#   when: not silent|bool